const SET_TOKEN = 'SET_TOKEN'
const ADD_AUTH_ERR = 'ADD_AUTH_ERR'
const SET_JOGS = 'SET_JOGS'
const TOGGLE_FILTER = 'TOGGLE_FILTER'
const TOGGLE_MODAL = 'TOGGLE_MODAL'
const ON_CHANGE = 'ON_CHANGE'
const POST_JOG = 'POST_JOG'

export {
  SET_TOKEN,
  ADD_AUTH_ERR,
  SET_JOGS,
  TOGGLE_FILTER,
  TOGGLE_MODAL,
  ON_CHANGE,
  POST_JOG
}