const SET_TOKEN = 'SET_TOKEN'
const ADD_AUTH_ERR = 'ADD_AUTH_ERR'
const SET_JOGS = 'SET_JOGS'
const TOGGLE_FILTER = 'TOGGLE_FILTER'
const TOGGLE_MODAL = 'TOGGLE_MODAL'
const ON_CHANGE = 'ON_CHANGE'
const DELETE_JOG = 'DELETE_JOG'
const CLEAR_ADD_FORM = 'CLEAR_ADD_FORM'
const PUSH_ADD_FORM = 'PUSH_ADD_FORM'
const SWITCH_MODAL = 'SWITCH_MODAL'
const CHANGE_FILTER_FROM = 'CHANGE_FILTER_FROM'
const CHANGE_FILTER_TO = 'CHANGE_FILTER_TO'
const CHANGE_MODAL_DATE = 'CHANGE_MODAL_DATE'
const MOBILE_CLICK_JOG = 'MOBILE_CLICK_JOG'

export {
  SET_TOKEN,
  ADD_AUTH_ERR,
  SET_JOGS,
  TOGGLE_FILTER,
  TOGGLE_MODAL,
  ON_CHANGE,
  DELETE_JOG,
  CLEAR_ADD_FORM,
  PUSH_ADD_FORM,
  SWITCH_MODAL,
  CHANGE_FILTER_FROM,
  CHANGE_FILTER_TO,
  CHANGE_MODAL_DATE,
  MOBILE_CLICK_JOG,
}